name: Plant Disease Detection CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt file found"; fi

    - name: Validate Streamlit Startup
      run: |
        python - <<EOF
        import streamlit
        import tensorflow as tf
        print("Streamlit version:", streamlit.__version__)
        print("TensorFlow version:", tf.__version__)
        EOF

    - name: Run Basic Syntax Check
      run: |
        python -m py_compile **/*.py || echo " Python syntax errors found!"
